apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.podLabels }}
  name: {{ .Values.podLabels }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.podLabels }}
status:
  loadBalancer: {}