apiVersion: batch/v1
kind: Job
metadata:
  name: astar-client-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: astar-client
        image: astar-client:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: astar-parallel-cm
      restartPolicy: Never
  completions: 2
  parallelism: 2
