apiVersion: batch/v1
kind: Job
metadata:
  name: astar-search-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: astar-search
        image: astarsearch:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: astar-cm
      restartPolicy: Never
